# Generated by Django 4.2.7 on 2025-11-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
