# Generated by Django 4.2.7 on 2025-11-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_contact_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Job title (e.g., Full Stack Developer)",
                        max_length=200,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        help_text="Department (e.g., Engineering, Marketing)",
                        max_length=100,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("on-site", "On-site"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="remote",
                        max_length=100,
                    ),
                ),
                (
                    "location_details",
                    models.CharField(
                        blank=True,
                        help_text="Specific location if applicable",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full-time"),
                            ("part-time", "Part-time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        default="full-time",
                        max_length=20,
                    ),
                ),
                (
                    "experience_required",
                    models.CharField(
                        help_text="e.g., 2-4 years, Entry Level, Senior", max_length=50
                    ),
                ),
                (
                    "required_skills",
                    models.TextField(
                        help_text="Comma-separated skills (e.g., React, Node.js, Python)"
                    ),
                ),
                (
                    "preferred_skills",
                    models.TextField(
                        blank=True, help_text="Optional/preferred skills", null=True
                    ),
                ),
                ("description", models.TextField(help_text="Brief job description")),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True,
                        help_text="Key responsibilities (use line breaks for bullet points)",
                        null=True,
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(
                        blank=True,
                        help_text="Required qualifications and requirements",
                        null=True,
                    ),
                ),
                (
                    "salary_range",
                    models.CharField(
                        blank=True,
                        help_text="e.g., $50k-$70k, Competitive",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "benefits",
                    models.TextField(
                        blank=True, help_text="Benefits offered", null=True
                    ),
                ),
                ("application_deadline", models.DateField(blank=True, null=True)),
                (
                    "application_email",
                    models.EmailField(
                        default="hr@growthifyservices.in", max_length=254
                    ),
                ),
                (
                    "external_application_url",
                    models.URLField(
                        blank=True,
                        help_text="External job posting URL if any",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show this job on the website"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Feature this job at the top"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Job Opening",
                "verbose_name_plural": "Job Openings",
                "ordering": ["-is_featured", "order", "-created_at"],
            },
        ),
    ]
